version: '3.0'
services:
  # Zookeeper 서비스
  zookeeper:
    # 사용할 이미지
    image: wurstmeister/zookeeper
    # 컨테이너명 설정
    container_name: zookeeper_container
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "2182:2181"
  # Kafka 서비스
  kafka:
    # 사용할 이미지
    image: wurstmeister/kafka
    # 컨테이너명 설정
    container_name: kafka_container
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "9093:9092"
    # 환경 변수 설정
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "Topic:1:1, Topic:N:M"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    # 볼륨 설정
    volumes:
      - /var/run/docker.sock
    # 의존 관계 설정
    depends_on:
      - zookeeper
  # Redis 서비스
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6380:6379"
  # MySQL 서비스
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: doguin
  # MongoDB 서비스
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27018:27017"