services:
  # Redis 서비스
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
  # MySQL 서비스
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: doguin
  # MongoDB 서비스
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"