services:
  # Redis 서비스
  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6380:6379"
  # MySQL 서비스
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '!@Skdud340'
      MYSQL_DATABASE: doguin
  # MongoDB 서비스
  mongodb:
    image: mongo
    container_name: mongo_container
    ports:
      - "27018:27017"
  # Doguin 애플리케이션 서비스
  doguin:
    image: tiyu25/doguin:latest   # doguin 이미지 명시
    container_name: doguin_container
    ports:
      - "8081:8081"               # 외부 포트와 매핑
    depends_on:
      - redis                     # redis, mysql, mongodb가 실행된 후 실행
      - mysql
      - mongodb
